### ISSUE TITLE
"an implementation is missing" when parsing case classes

### ISSUE THREAD

**Issue by tyrcho** [propensive/rapture-json#34]
Here is a sample to reproduce the issue 

```scala
case class Action(
  time: Int,
  action: String,
  card: Option[String],
  cardId: Int,
  player: Int,
  target: Option[Int] = None)


case class Turn(actions: List[Action] = Nil)

case class GameLog(
  //Note : the head of the list is actually the last turn (order is reversed)
  turns: List[Turn] = List(Turn()),
  firstPlayer: Option[Int] = None,
  secondPlayer: Option[Int] = None,
  firstPlayerName: Option[String] = None,
  secondPlayerName: Option[String] = None)

val gl=GameLog()

val j=Json(gl)
```

==>
scala.NotImplementedError: an implementation is missing
  at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
  at rapture.json.jsonBackends.jackson.internal.JacksonAst$.nullValue(ast.scala:108)
  at rapture.json.jsonBackends.jackson.internal.JacksonAst$.nullValue(ast.scala:33)
  at rapture.json.internal.Serializers$$anonfun$optionSerializer$1.apply(serializers.scala:83)
  at rapture.json.internal.Serializers$$anonfun$optionSerializer$1.apply(serializers.scala:83)
  at rapture.json.internal.Serializers$BasicJsonSerializer.serialize(serializers.scala:38)
  at $anon$3.serialize(<console>:36)
  at $anon$3.serialize(<console>:36)
  at rapture.data.DataCompanion$class.apply(data.scala:54)
  at rapture.json.Json$.apply(json.scala:101)

**Comment by tyrcho** [comment]
Note that I have a similar error with an initialized object

GameLog(List(Turn(List(Action(1,,None,5,3,None)))),None,None,None,None)

==>

scala.NotImplementedError: an implementation is missing
  at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
  at rapture.json.jsonBackends.jackson.internal.JacksonAst$.nullValue(ast.scala:108)
  at rapture.json.jsonBackends.jackson.internal.JacksonAst$.nullValue(ast.scala:33)
  at rapture.json.internal.Serializers$$anonfun$optionSerializer$1.apply(serializers.scala:83)
  at rapture.json.internal.Serializers$$anonfun$optionSerializer$1.apply(serializers.scala:83)
  at rapture.json.internal.Serializers$BasicJsonSerializer.serialize(serializers.scala:38)
  at $anon$1.serialize(<console>:26)
  at $anon$1.serialize(<console>:26)
  at rapture.json.internal.Serializers$$anonfun$traversableSerializer$1$$anonfun$apply$1.apply(serializers.scala:79)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.immutable.List.foreach(List.scala:383)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.immutable.List.map(List.scala:286)
  at rapture.json.internal.Serializers$$anonfun$traversableSerializer$1.apply(serializers.scala:79)
  at rapture.json.internal.Serializers$$anonfun$traversableSerializer$1.apply(serializers.scala:79)
  at rapture.json.internal.Serializers$BasicJsonSerializer.serialize(serializers.scala:38)
  at $anon$2.serialize(<console>:26)
  at $anon$2.serialize(<console>:26)
  at rapture.json.internal.Serializers$$anonfun$traversableSerializer$1$$anonfun$apply$1.apply(serializers.scala:79)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.immutable.List.foreach(List.scala:383)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.immutable.List.map(List.scala:286)
  at rapture.json.internal.Serializers$$anonfun$traversableSerializer$1.apply(serializers.scala:79)
  at rapture.json.internal.Serializers$$anonfun$traversableSerializer$1.apply(serializers.scala:79)
  at rapture.json.internal.Serializers$BasicJsonSerializer.serialize(serializers.scala:38)
  at $anon$3.serialize(<console>:26)
  at $anon$3.serialize(<console>:26)
  at rapture.data.DataCompanion$class.apply(data.scala:54)
  at rapture.json.Json$.apply(json.scala:101)
  ... 53 elided

**Comment by tyrcho** [comment]
Simpler test case : (same case class Action)

```scala
Json(res4)

res6: rapture.json.Json = {"cardId":3,"player":5,"target":8,"time":1,"card":"az","action":"aa"}


res4.copy(card=None)

res7: Action = Action(1,aa,None,3,5,Some(8))


Json(res7)

scala.NotImplementedError: an implementation is missing

**Comment by tyrcho** [comment]
Seems that it cannot parse when the Option is None :s

**Comment by propensive** [comment]
My guess is that it's a problem with the Jackson backend, but I'll investigate now. Are you able to try with a different backend, e.g. Jawn?

**Comment by propensive** [comment]
Right, that works fine using Jawn instead of Jackson, so it's an integration problem. I'll try to work out what's going wrong there.

**Comment by propensive** [comment]
For some reason (my carelessness), that wasn't properly implemented in the Jackson integration. I've implemented it correctly now, so it runs without the exception, though there remains a limitation in that serialization will serialize a `None` to a `null`, rather than just not including the default value. The fix will go into the next minor release.

I'll open a new issue regarding that, because it's not entirely straightforward - sometimes you want to serialize `null`s.

Thanks for finding this!

**Comment by propensive** [comment]
Issue #35 created.

**Comment by tyrcho** [comment]
I confirm it works fine with jawn. Thanks for the prompt answer !
