### ISSUE TITLE
undefined and Json.format

### ISSUE THREAD

**Issue by byF** [propensive/rapture-json#43]
I've got a `Seq[Map[String, Json]]`. When the content of the map is like `val thatSeq = Seq(Map("a"->undefined,"b"->undefined))`, calling `val j = Json(thatSeq)` produces just `undefined`.

Then calling `Json.format(j)` fails with 
```
Type mismatch: Expected number but found number at <value>
rapture.data.TypeMismatchException: Type mismatch: Expected number but found number at <value>
```

I believe the `Json(thatSeq)` should not reduce the whole call into one `undefined`; 

One minor thing, JSON parser doesn't allow definitions such as json"undefined", json"[undefined]", etc - so it's not possible to test again it anyway.

**Comment by propensive** [comment]
Hi Zdenek,

Thanks for reporting this! I've tried to reproduce the problem, and I found
I got a correct error when constructing `Json(thatSeq)`, but that may be
due to how I attempted to create the `undefined` values.

Here's what I did:

val undef = json"{}".missing
val thatSeq = Seq[Map[String, Json]](Map("foo" -> undef))
Json(thatSeq)

This reports the error "Missing value: <value>.missing", which is exactly
what you should expect when trying to access a key that isn't there. But if
you've created your "undefined" values a different way, then that might
cause different behavior. Either way, the error message you're seeing
("expected number, but found number") isn't correct, but that may be
something I've fixed in the current unreleased version.

Also, which JSON backend are you using?

Regarding creating your own "undefined" values, whenever you see
"undefined" that only ever exists as the result of a call to `toString`,
and is because we allow "illegal" JSON to exist while we're in the dynamic
world, right up until the point we convert it to a static Scala type, by
calling `as[SomeType]` on it. The alternative is that exceptions could
potentially be thrown for every single object access, e.g. in three places
if you call `json.foo.bar.baz`. But I didn't want this (which becomes
particularly problematic if you are using modes like `returnTry`), so it
was a design decision to be permissive of runtime errors while still
working with dynamically-typed JSON, right up to the point where you move
to the static world.

Conseqently, we don't want a call to `toString` to ever throw an exception,
so we just return `undefined`. Just returning `null` would have been an
alternative. It's discouraged to use `toString` for converting `Json` to a
string, in favor of the `Json.format` method which will (correctly) throw
an exception if it encounters bad JSON.

Anyway, if you could send me the extra information, I can investigate this
further!

Cheers,
Jon

On 16 February 2015 at 09:56, Zdenek Farana <notifications@github.com>
wrote:

> I've got a Seq[Map[String, Json]]. When the content of the map is like val
> thatSeq = Seq(Map("a"->undefined,"b"->undefined)), calling val j =
> Json(thatSeq) produces just undefined.
>
> Then calling Json.format(j) fails with
>
> Type mismatch: Expected number but found number at <value>
> rapture.data.TypeMismatchException: Type mismatch: Expected number but found number at <value>
>
> I believe the Json(thatSeq) should not reduce the whole call into one
> undefined;
>
> One minor thing, JSON parser doesn't allow definitions such as
> json"undefined", json"[undefined]", etc - so it's not possible to test
> again it anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/propensive/rapture-json/issues/43>.
>



-- 
Jon Pretty | @propensive

**Comment by byF** [comment]
Well, I'm constructing JSON with a bit of bending. If you remember, once I asked you how to jsonize Map[String,Any]. Unfortunately, I was not able to make it work using solution you proposed in a gist (wrapping it at the time of creation) since I ran into other problems with that.

So, there was an easy, albeit not that type-safe solution; using spray-json:

`MyJsonProtocol extends spray.json.DefaultJsonProtocol` contains two implicits which helps serializing and deserializing `Any`; both input and output types are limited, so the type-safety is really not a big concern. When I import it into a scope, I can simply do `Json(anyMap.toJson)` where `toJson` is spray-json implicit. This actually works very nicely and correctly except for this one corner case.

The reason why I keep using Rapture instead of just plain spray-json
- accessing JSON values feels way more natural using Dynamic
- tests are much more readable

Anyhow, this is how I'm getting to those undefineds.

**Comment by propensive** [comment]
Hi Zdenek!

Ok, so have I got this right?

Given that Rapture JSON with the Spray backend will allow creation of a
Rapture `Json` object from Spray `JsValue` or `JsObject` values, you're
just converting the `Map[String, Any]` into a `JsObject` before passing it
to Rapture?

And the `JsObject`s that you're creating may therefore contain "bad" data,
but the `JsObject` type is happy just to accept that? (I guess, in the same
way that Rapture is happy for `undefined`s to exist.)

The backend integration for Spray contains a method for testing whether a
given value is a number, and a method for getting that number, and these
are just implemented to delegate to Spray's methods for the same thing.
It's conceivable that a value is returning `true` for the `isNumber` test,
then failing for the `getDouble` extractor, but I would need to investigate
further.

What do you think is the best way forward? Could you give me enough code to
reproduce the error?

Thanks,
Jon



On 16 February 2015 at 21:12, Zdenek Farana <notifications@github.com>
wrote:

> Well, I'm constructing JSON with a bit of bending. If you remember, once I
> asked you how to jsonize Map[String,Any]. Unfortunately, I was not able to
> make it work using solution you proposed in a gist (wrapping it at the time
> of creation) since I ran into other problems with that.
>
> So, there was an easy, albeit not that type-safe solution; using
> spray-json:
>
> MyJsonProtocol extends spray.json.DefaultJsonProtocol contains two
> implicits which helps serializing and deserializing Any; both input and
> output types are limited, so the type-safety is really not a big concern.
> When I import it into a scope, I can simply do Json(anyMap.toJson) where
> toJson is spray-json implicit. This actually works very nicely and
> correctly except for this one corner case.
>
> The reason why I keep using Rapture instead of just plain spray-json
>
>    - accessing JSON values feels way more natural using Dynamic
>    - tests are much more readable
>
> Anyhow, this is how I'm getting to those undefineds.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/propensive/rapture-json/issues/43#issuecomment-74573160>
> .
>



-- 
Jon Pretty | @propensive

**Comment by byF** [comment]
Yes I'm passing JsObject to Rapture. I reviewed our code and something is fishy there; The final step of the serialization is

```scala
val seq: Seq[Map[String,Json]] = results.map{...}.toSeq
Json(seq)
```

When the problem is happening,`results` is an empty iterator of type `Iterator[Map[String, Any]]`; Intellij debugger says `seq` type is `scala.collection.immutable.Stream.Empty`; I guess that explains why `Json(seq)` has actual value `undefined` (that's what I see in the debugger).

However, I found the problem happens in other cases as well. Simply try:

`Json.format(json"""{"x": null}""")`

Also fails with 

```
Type mismatch: Expected number but found number at <value>
rapture.data.TypeMismatchException: Type mismatch: Expected number but found number at <value>
	at rapture.json.jsonBackends.spray.internal.SprayAst$.getBigDecimal(ast.scala:75)
	at rapture.json.internal.formatters_1.general(formatters.scala:60)
	at rapture.json.internal.formatters_1$$anonfun$general$2.apply(formatters.scala:71)
	at rapture.json.internal.formatters_1$$anonfun$general$2.apply(formatters.scala:69)
```

**Comment by propensive** [comment]
Right, this looks like an issue specific to Rapture JSON's Spray integration, at least with the handling of `null`. That example fails in Spray, works fine in Jawn, and fails (in a different way) with the Standard Library JSON backend. I'll try the other backends and see if I can work out where the problem is.

**Comment by propensive** [comment]
By the way, the currently-released Spray integration uses Rapture's "generic" formatter when you call `Json.format(...)`, though in the next release I will update it to use Spray's own (by default). This may work better...
